[project]
name = "velma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.0",
    "ipykernel>=6.29.5",
    "jinja2>=3.1.6",
    "vllm>=0.8.4",
]
